---
title: "Changing intercepts"
output: html_notebook
author: "Ann-Kathrin Pohle"
---

Values obtained by using this code were manually extracted and stored in separate .csv files named vol_models, bh_models and bw_models. For simplification we did not extract interaction terms.

```{r setting different intercepts}

minks_nov_wild_f <- minks_nov
minks_nov_wild_f$Category <- factor(minks_nov_wild_f$Category, levels = c("wild", "farm", "feral")) #original wild female

minks_nov_wild_m <- minks_nov
minks_nov_wild_m$sex <- factor(minks_nov_wild_m$sex, levels = c("M", "F")) #wild male
vol_m <- lm(volcbl3_big ~ sex*Category, data = minks_nov_wild_m)

minks_nov_feral_f <- minks_nov
minks_nov_feral_f$Category <- factor(minks_nov_feral_f$Category, levels = c("feral", "farm", "wild")) #feral female


minks_nov_feral_m <- minks_nov_feral_f
minks_nov_feral_m$sex <- factor(minks_nov_feral_m$sex, levels = c("M", "F")) #feral male

minks_nov_farm_f <- minks_nov
minks_nov_farm_f$Category <- factor(minks_nov_farm_f$Category, levels = c("farm", "feral", "wild")) #farm female

minks_nov_farm_m <- minks_nov_farm_f
minks_nov_farm_m$sex <- factor(minks_nov_farm_m$sex, levels = c("M", "F")) #farm male

```


```{r vol models}
#vol_cat is the original model with female wild as intercept
vol_cat2 <- glm(volcbl3_big ~ sex*Category, data = minks_nov)
a <- coef(summary(vol_cat2))
volcat2df <- as.data.frame(a) #not completely necessary can just call a and get the same results
confint.default(vol_cat2, level = 0.95)

vol_wild_m <- glm(volcbl3_big ~ sex*Category, data = minks_nov_wild_m)
b <- coef(summary(vol_wild_m))
confint.default(vol_wild_m, level = 0.95)

vol_feral_f <- glm(volcbl3_big ~ sex*Category, data = minks_nov_feral_f)
c <- coef(summary(vol_feral_f))
vol_feral_f_df <- as.data.frame(c)
confint.default(vol_feral_f, level = 0.95)

vol_feral_m <- glm(volcbl3_big ~ sex*Category, data = minks_nov_feral_m)
d <- coef(summary(vol_feral_m))
vol_feral_m_df <- as.data.frame(d)
confint.default(vol_feral_m, level = 0.95)

vol_farm_f <- glm(volcbl3_big ~ sex*Category, data = minks_nov_farm_f)
e <- coef(summary(vol_farm_f))
vol_farm_f_df <- as.data.frame(e)
confint.default(vol_farm_f, level = 0.95)

vol_farm_m <- glm(volcbl3_big ~ sex*Category, data = minks_nov_farm_m)
f <- coef(summary(vol_farm_m))
vol_farm_m_df <- as.data.frame(f)
confint.default(vol_farm_m, level = 0.95)

```

```{r bh models}

bh_cat2 <- lm(bhcbl_big ~ sex*Category, data = minks_nov)
g <- coef(summary(bh_cat2))
confint.default(bh_cat2, level = 0.95)

bh_wild_m <- lm(bhcbl_big ~ sex*Category, data = minks_nov_wild_m)
h <- coef(summary(bh_wild_m))
confint.default(bh_wild_m, level = 0.95)

bh_feral_f <- lm(bhcbl_big ~ sex*Category, data = minks_nov_feral_f)
i <- coef(summary(bh_feral_f))
confint.default(bh_feral_f, level = 0.95)

bh_feral_m <- lm(bhcbl_big ~ sex*Category, data = minks_nov_feral_m)
j <- coef(summary(bh_feral_m))
confint.default(bh_feral_m, level = 0.95)

bh_farm_f <- lm(bhcbl_big ~ sex*Category, data = minks_nov_farm_f)
k <- coef(summary(bh_farm_f))
confint.default(bh_farm_f, level = 0.95)

bh_farm_m <- lm(bhcbl_big ~ sex*Category, data = minks_nov_farm_m)
l <- coef(summary(bh_farm_m))
confint.default(bh_farm_m, level = 0.95)

```



```{r bw models}

bw_cat2 <- lm(bwcbl_big ~ sex*Category, data = minks_nov)
m <- coef(summary(bw_cat2))
confint.default(bw_cat2, level = 0.95)

bw_wild_m <- lm(bwcbl_big ~ sex*Category, data = minks_nov_wild_m)
n <- coef(summary(bw_wild_m))
confint.default(bw_wild_m, level = 0.95)

bw_feral_f <- lm(bwcbl_big ~ sex*Category, data = minks_nov_feral_f)
o <- coef(summary(bw_feral_f))
confint.default(bw_feral_f, level = 0.95)

bw_feral_m <- lm(bwcbl_big ~ sex*Category, data = minks_nov_feral_m)
p <- coef(summary(bw_feral_m))
confint.default(bw_feral_m, level = 0.95)

bw_farm_f <- lm(bwcbl_big ~ sex*Category, data = minks_nov_farm_f)
q <- coef(summary(bw_farm_f))
confint.default(bw_farm_f, level = 0.95)

bw_farm_m <- lm(bwcbl_big ~ sex*Category, data = minks_nov_farm_m)
r <- coef(summary(bw_farm_m))
confint.default(bw_farm_m, level = 0.95)

```

